In [298]:
from PIL import Image
import math
import numpy as np

"""
mapped_sum_gradient_iguanaet and use the functions associated with gaussconvolve2d that you used in the last HW02.
"""
def gauss1d(sigma):
    width: int = int(math.ceil(6 * sigma))  # 6*sigma의 다음 정수로 width를 설정
    if width % 2 == 0:  # 다음 정수가 짝수라면 +1 하여 홀수로 변경
        width += 1

    center = math.floor(width / 2)  # 가운데 index를 획득
    gaussian = np.zeros((1, width)).flatten()  # 반환할 1D Numpy Array 생성
    for i in range(width):
        gaussian[i] = i - center  # Hint:를 토대로 x값을 입력
    for i in range(width):
        gaussian[i] = math.exp(-gaussian[i] ** 2 / (2 * sigma ** 2))  # x값에 따라 gaussian값 획득 및 입력

    # 아래는 normalize, 전체 합으로 각 엔트리를 나눈다.
    kernal_sum = np.sum(gaussian)
    for i in range(width):
        gaussian[i] /= kernal_sum
    return gaussian

def gauss2d(sigma):
    return np.outer(gauss1d(sigma), gauss1d(sigma))
# outer product로 2d 가우시안 필터를 구한다.

def convolve2d(array, filter):
    padding_width = int(len(filter) / 2)  # filter에 따른 padding 크기
    zero_padding = np.zeros((np.shape(array)[0] + padding_width * 2,
                             np.shape(array)[1] + padding_width * 2))
    # padding한 크기에 맞게 새로운 np.array를 생성

    # convolution연산을 위해서 filter를 축의 방향에 대해서 뒤집는다.
    flipped_filter = np.flip(filter, axis=0)
    flipped_filter = np.flip(flipped_filter, axis=1)
    # 모든 픽셀에 대해서 paading을 제외한 부분에 array를 집어넣어 준다.
    for i in range(padding_width, np.shape(zero_padding)[0] - padding_width):
        for j in range(padding_width, np.shape(zero_padding)[1] - padding_width):
            zero_padding[i][j] = array[i - padding_width][j - padding_width]

    # padding된 이미지의 각 픽셀을 순회하면서 각 픽셀에 컨벌루젼한 값을 입력한다.

    convolved = np.zeros(np.shape(array))

    for i in range(padding_width, np.shape(zero_padding)[0] - padding_width):
        for j in range(padding_width, np.shape(zero_padding)[1] - padding_width):
            subpart = zero_padding[i - padding_width:i + padding_width + 1,
                      j - padding_width:j + padding_width + 1]
            convolved[i-padding_width][j-padding_width] = np.sum(subpart * flipped_filter)
    # 컨벌루젼한 값을 리턴
    return convolved

def gaussconvolve2d(array, sigma):
    return convolve2d(array, gauss2d(sigma))


In [299]:
# 이구아나 사진을 불러온다.
iguana_img = Image.open('iguana.bmp')
# 사진을 흑백처리한다.
iguana_img_grey = iguana_img.convert('L')
# 이미지를 np 배열형태로 변형한다.
iguana_array_grey = np.asarray(iguana_img_grey)
# 가우시안 필터 효과를 적용한다.
iguana_array_grey_blur = np.uint8(gaussconvolve2d(iguana_array_grey, 1.6))
# 배열을 이미지로 변경하여 보여준다.
Image.fromarray(iguana_array_grey_blur).show()

In [300]:
#sobel연산을 위한 필터를 제작한다. normalization을 위해 8로 나눈다.
x_sobel = np.array([ 1, 0, -1, 2, 0, -2, 1, 0, -1])
y_sobel = np.array([ 1, 2, 1, 0, 0, 0, -1, -2, -1])
x_sobel = x_sobel.reshape((3, 3))/8.0
y_sobel = y_sobel.reshape((3, 3))/8.0

In [301]:
# sobel
x_gradient_iguana = convolve2d(iguana_array_grey_blur, x_sobel)
y_gradient_iguana = convolve2d(iguana_array_grey_blur, y_sobel)

In [302]:
sum_gradient_iguana = np.hypot(x_gradient_iguana, y_gradient_iguana)
max_intense = np.max(sum_gradient_iguana)
mapped_sum_gradient_iguana = (sum_gradient_iguana / np.max(sum_gradient_iguana)) * 255

In [303]:
Image.fromarray(mapped_sum_gradient_iguana).show()

In [304]:
vectorized_arctan = np.vectorize(np.arctan)
x_gradient_iguana[x_gradient_iguana==0] = 0.000001
theta = vectorized_arctan(y_gradient_iguana/x_gradient_iguana)
print(theta)
print(np.max(theta))
print(np.min(theta))

theta_degree = theta * 180 / np.pi
# 변환된 각도에 따라 매핑한다. 매핑은 0 ~
theta_mapped = (theta_degree + 22.5) // 45
print(theta_degree)
print(np.max(theta_degree))
print(np.min(theta_degree))
print("------")
print(theta_mapped)
print(np.max(theta_mapped))
print(np.min(theta_mapped))

[[ 0.78539816  1.34656158  1.50837752 ... -1.47584462 -1.31847835
  -0.77933763]
 [ 0.26916749  0.87605805  1.31712223 ... -1.18726881 -0.76540083
  -0.24039574]
 [ 0.13352905  0.51445131  1.05165021 ... -0.83620187 -0.41507473
  -0.11140127]
 ...
 [ 0.23374318  0.68231655  0.95613337 ... -1.57079627  1.00748007
   0.23915025]
 [ 0.05549851  0.20749623  0.38050638 ... -1.45868562  1.25830477
   0.35926646]
 [-0.68572951 -1.18563882 -1.31561394 ... -1.48425503  1.4868817
   0.84247895]]
1.5707963074712252
-1.5707963153335787
[[ 45.          77.15229514  86.42366563 ... -84.55966797 -75.5432446
  -44.6527571 ]
 [ 15.42216132  50.19442891  75.46554492 ... -68.02549201 -43.85423716
  -13.77366153]
 [  7.65065096  29.475889    60.2551187  ... -47.91083783 -23.78203042
   -6.38282253]
 ...
 [ 13.39249775  39.09385889  54.78240703 ... -89.99999673  57.72435569
   13.70230016]
 [  3.17983012  11.88865804  21.80140949 ... -83.57652956  72.09555249
   20.58445165]
 [-39.28940686 -67.93210044 -75

theta 를 매핑하고 0/45/90/135
매핑된 결과에 따라서 가장 큰 값을 적용

In [305]:
def remain_max(array, x, y, angle):
    ret = 0
    if angle == -2 or angle == 2:
        if array[y][x] < max(array[y+1][x], array[y][x], array[y-1][x]):
            ret = 0
        else:
            ret =  array[y][x]
    if angle == -1:
        if array[y][x] < max(array[y+1][x-1], array[y][x], array[y-1][x+1]):
            ret =  0
        else:
            ret =  array[y][x]
    if angle == 0:
        if array[y][x] < max(array[y][x+1], array[y][x], array[y][x-1]):
            ret = 0
        else:
            ret = array[y][x]
    if angle == 1:
        if array[y][x] < max(array[y+1][x+1], array[y][x], array[y-1][x-1]):
            ret = 0
        else:
            ret = array[y][x]
    return ret

In [306]:
res = np.zeros(np.shape(mapped_sum_gradient_iguana))
for row in range(1, len(mapped_sum_gradient_iguana)-1):
    for col in range(1, len(mapped_sum_gradient_iguana[1])-1):
        res[row][col] = \
            remain_max(mapped_sum_gradient_iguana, col, row, theta_mapped[row][col])
Image.fromarray(res).show()

In [307]:
def theta_mapping(angle):
    if angle == -2 or angle == 2:
        return np.array([128,0,0])
    if angle == -1:
        return np.array([0,128,0])
    if angle == 0:
        return np.array([0,0,128])
    if angle == 1:
        return np.array([128,128,128])

In [308]:
mapped_theta = np.zeros((len(theta), len(theta[0]), 3))
for i in range(len(mapped_theta)):
    for j in range(len(mapped_theta[0])):
        for k in range(3):
            mapped_theta[i][j][k] = theta_mapping(theta_mapped[i][j])[k]

print(mapped_theta)
Image.fromarray(mapped_theta.astype(np.uint8)).show()

[[[128. 128. 128.]
  [128.   0.   0.]
  [128.   0.   0.]
  ...
  [128.   0.   0.]
  [128.   0.   0.]
  [  0. 128.   0.]]

 [[  0.   0. 128.]
  [128. 128. 128.]
  [128.   0.   0.]
  ...
  [128.   0.   0.]
  [  0. 128.   0.]
  [  0.   0. 128.]]

 [[  0.   0. 128.]
  [128. 128. 128.]
  [128. 128. 128.]
  ...
  [  0. 128.   0.]
  [  0. 128.   0.]
  [  0.   0. 128.]]

 ...

 [[  0.   0. 128.]
  [128. 128. 128.]
  [128. 128. 128.]
  ...
  [128.   0.   0.]
  [128. 128. 128.]
  [  0.   0. 128.]]

 [[  0.   0. 128.]
  [  0.   0. 128.]
  [  0.   0. 128.]
  ...
  [128.   0.   0.]
  [128.   0.   0.]
  [  0.   0. 128.]]

 [[  0. 128.   0.]
  [128.   0.   0.]
  [128.   0.   0.]
  ...
  [128.   0.   0.]
  [128.   0.   0.]
  [128. 128. 128.]]]


Theta는 제대로 작동하는 것처럼 보이는데....